require("nvim-tree").setup()
local api = require("nvim-tree.api")
vim.keymap.set("n", "<leader>e", api.tree.toggle, {})
vim.keymap.set("n", "<leader>1", api.tree.toggle, {})
vim.keymap.set("n", "<F8>", function() api.tree.toggle({ find_file=true }) end, {})
